### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TrulyBright** [TrulyBright/YoonDong-ju#1]
# Frontend
- [x] Breadcrumb 비슷한 Index.
- [x] 새로고침 시 로그인 풀리는 문제. (쿠키 必)
- [x] 회원관리 메뉴 디자인
- [x] 문집 메뉴 디자인
- [x] 내정보 화면
- [x] 회원탈퇴 기능
- [ ] 버튼에 다 spinner
- [x] 업로드에 Progressbar
- [ ] 페이지 변경 시 spinner
- [x] notice list 디자인
- [x] logout 기능
- [x] Post에 사진 첨부

# Backend
- [ ] '분반' 활동 기록률 저조...삭제하기?... ㅠㅠ
- [ ] 도서대출/반납 기능 추가.
- [ ] 대문 화면에서는 문집 원본 사진 말고 Thumbnail 보여주기?
- [ ] Type: posts.no 관계가 담긴 SpecialPost schema를 만들어 현 about/rules가 DB에 구현된 방식을 대체할 필요.
- [x] Post 삭제 시 연관된 UploadedFile도 /uploaded 디렉토리에서 자동 삭제

# Front & Back
- [x] 계정명/비밀번호 찾기
